/*
 * This file is generated by jOOQ.
 */
package horse.boo.database.jooq.model.tables.records;


import horse.boo.database.jooq.model.tables.Ponies;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoniesRecord extends UpdatableRecordImpl<PoniesRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1100373873;

    /**
     * Setter for <code>public.ponies.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ponies.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ponies.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ponies.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ponies.age</code>.
     */
    public void setAge(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ponies.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Ponies.PONIES.PONIES_ID;
    }

    @Override
    public Field<String> field2() {
        return Ponies.PONIES.PONIES_NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Ponies.PONIES.PONIES_AGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAge();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAge();
    }

    @Override
    public PoniesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PoniesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PoniesRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public PoniesRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PoniesRecord
     */
    public PoniesRecord() {
        super(Ponies.PONIES);
    }

    /**
     * Create a detached, initialised PoniesRecord
     */
    public PoniesRecord(Integer id, String name, Integer age) {
        super(Ponies.PONIES);

        set(0, id);
        set(1, name);
        set(2, age);
    }
}
