/*
 * This file is generated by jOOQ.
 */
package jooq.model;


import jooq.model.tables.Ponies;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ponies</code>.
     */
    public static final Ponies PONIES = Ponies.PONIES;
}
